tunnel: <cloudflare-tunnel-id>
credentials-file: /home/powell/.cloudflared/<cloudflare-tunnel-id>.json

ingress:
  - hostname: pi.pwll.dev
    service: http://localhost:8000
  - hostname: boot.pi.pwll.dev
    service: http://localhost:9000
  - hostname: ssh.pi.pwll.dev
    service: ssh://localhost:22
  - service: http_status:404
